name: dots_indicator_example
description: Demonstrates how to use the dots_indicator plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dots_indicator:
    path: ../

flutter:
  uses-material-design: true