name: dots_indicator
description: Dots indicator to show progression of a PageView for example
version: 3.0.0
homepage: https://github.com/pyozer/dots_indicator

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
