name: dots_indicator
description: Dots indicator to show progression of a PageView for example
version: 2.1.0
homepage: https://github.com/pyozer/dots_indicator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
